channels:
- conda-forge
dependencies:
- ca-certificates=2026.1.4
- mkdocs=1.6.1
- mkdocs-material=9.7.0
- openssl=3.6.1
- pymdown-extensions=10.17.2
- python=3.14.0
- numpy=2.3.5
- python-dotenv=1.2.1
